# Generated by Django 3.1.1 on 2021-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='poll.Tag'),
        ),
    ]
